
-- DROP TABLE public.rend25_rendement;

CREATE TABLE public.rend25_rendement (
                                         id  SERIAL NOT NULL,
                                         mois varchar(10) NULL,
                                         annee int4 NULL,
                                         dr varchar(50) NULL,
                                         idd varchar(50) NULL,
                                         brigade varchar NULL,
                                         wilaya varchar(100) NULL,
                                         collab varchar(255) NULL,
                                         loc_e numeric(10, 6) NULL,
                                         loc_n numeric(10, 6) NULL,
                                         topo varchar(255) NULL,
                                         "date" date NULL,
                                         heure time NULL,
                                         armes_u int4 NULL,
                                         type_armes varchar(255) NULL,
                                         mun_u int4 NULL,
                                         equip_sens_m numeric(12, 2) NULL,
                                         equip_sens_u int4 NULL,
                                         kif_kg numeric(12, 3) NULL,
                                         coc_kg numeric(12, 3) NULL,
                                         psy_compr int4 NULL,
                                         desc_prod text NULL,
                                         cig_u int8 NULL,
                                         tab_kg numeric(12, 2) NULL,
                                         alc_l numeric(12, 2) NULL,
                                         carb_l numeric(12, 2) NULL,
                                         alim_kg numeric(12, 2) NULL,
                                         alim_l numeric(12, 2) NULL,
                                         equip_sens_info varchar NULL,
                                         date_ varchar NULL,
                                         periode date NULL,
                                         latitude numeric(10, 6) NULL,
                                         longitude numeric(10, 6) NULL,
                                         CONSTRAINT rendement825_pkey PRIMARY KEY (id)
);


-- DROP TABLE public.rend24_rendement;

CREATE TABLE public.rend24_rendement (
                                         id  SERIAL NOT NULL,
                                         mois varchar(10) NULL,
                                         annee int4 NULL,
                                         dr varchar(50) NULL,
                                         idd varchar(50) NULL,
                                         brigade varchar NULL,
                                         wilaya varchar(100) NULL,
                                         collab varchar(255) NULL,
                                         loc_e numeric(10, 6) NULL,
                                         loc_n numeric(10, 6) NULL,
                                         topo varchar(255) NULL,
                                         "date" date NULL,
                                         heure time NULL,
                                         armes_u int4 NULL,
                                         type_armes varchar(255) NULL,
                                         mun_u int4 NULL,
                                         equip_sens_m numeric(12, 2) NULL,
                                         equip_sens_u int4 NULL,
                                         kif_kg numeric(12, 3) NULL,
                                         coc_kg numeric(12, 3) NULL,
                                         psy_compr int4 NULL,
                                         desc_prod text NULL,
                                         cig_u int8 NULL,
                                         tab_kg numeric(12, 2) NULL,
                                         alc_l numeric(12, 2) NULL,
                                         carb_l numeric(12, 2) NULL,
                                         alim_kg numeric(12, 2) NULL,
                                         alim_l numeric(12, 2) NULL,
                                         equip_sens_info varchar NULL,
                                         date_ varchar NULL,
                                         periode date NULL,
                                         latitude numeric(10, 6) NULL,
                                         longitude numeric(10, 6) NULL,
                                         CONSTRAINT rendement_24_pkey PRIMARY KEY (id)
);


CREATE TABLE public.rendement (
                                         id  SERIAL NOT NULL,
                                         mois varchar(10) NULL,
                                         annee int4 NULL,
                                         dr varchar(50) NULL,
                                         idd varchar(50) NULL,
                                         brigade varchar NULL,
                                         wilaya varchar(100) NULL,
                                         collab varchar(255) NULL,
                                         loc_e numeric(10, 6) NULL,
                                         loc_n numeric(10, 6) NULL,
                                         topo varchar(255) NULL,
                                         "date" date NULL,
                                         heure time NULL,
                                         armes_u int4 NULL,
                                         type_armes varchar(255) NULL,
                                         mun_u int4 NULL,
                                         equip_sens_m numeric(12, 2) NULL,
                                         equip_sens_u int4 NULL,
                                         kif_kg numeric(12, 3) NULL,
                                         coc_kg numeric(12, 3) NULL,
                                         psy_compr int4 NULL,
                                         desc_prod text NULL,
                                         cig_u int8 NULL,
                                         tab_kg numeric(12, 2) NULL,
                                         alc_l numeric(12, 2) NULL,
                                         carb_l numeric(12, 2) NULL,
                                         alim_kg numeric(12, 2) NULL,
                                         alim_l numeric(12, 2) NULL,
                                         equip_sens_info varchar NULL,
                                         date_ varchar NULL,
                                         periode date NULL,
                                         latitude numeric(10, 6) NULL,
                                         longitude numeric(10, 6) NULL,
                                         CONSTRAINT rendement_all_pkey PRIMARY KEY (id)
);